apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      label:
        component: web
    spec:
      - name: client
        image: reysmerwvr/multi-client
        ports:
          - containerPort: 3000